### ISSUE TITLE
Add appendObjectName

### ISSUE THREAD

**Issue by LucidComplex** [realm/realm-graphql-service#30]
Currently, the only way I can find to mutate an object with a collection is to update the collection and insert my new member of the collection along with the existing members.

Is it possible to have a mutation to append a list?

**Comment by nirinchev** [comment]
This is currently tracked in https://github.com/realm/realm-graphql-service/issues/28. It's not currently possible, but we're exploring options to enable that. In theory, it shouldn't be too hard to do but hasn't been prioritized yet.
