### ISSUE TITLE
Subscriptions get shared between clients

### ISSUE THREAD

**Issue by LucidComplex** [realm/realm-graphql-service#40]
Subscribe filters don't work properly when 2 different clients subscribing to the same object but with different filters. For example Client A runs:
```jsx
const query = gql`subscription {
  books(query: "author.name = 'Ernest Cline'") {
    lastReadDatetime
  }
}`
client.subscribe({ query }).subscribe({
  next: data => {
    console.log(data)
  },
  error: err => {
    console.log(err);
  }
})
```
Works great with only Client A running the code; however, when Client B runs
```jsx
const query = gql`subscription {
  books(query: "author.name = 'Charles Dickens'") {
    lastReadDatetime
  }
}`
client.subscribe({ query }).subscribe({
  next: data => {
    console.log(data)
  },
  error: err => {
    console.log(err);
  }
})
```
Both clients subscribe to both filters, switching between them for every update.

**Comment by LucidComplex** [comment]
I'd like to follow up on this issue

**Comment by mgeerling** [comment]
@LucidComplex , it doesn't look like you shared any kind of error message or the exact behavior you're seeing.  I just see two code snippets

**Comment by LucidComplex** [comment]
@mgeerling There is no error message. I believe I've clearly described the behavior that is occurring. The subscriptions are being shared. That is, when you subscribe to 2 different things, such as subscribing to 2 different authors, both observers receive update for both authors -- even updates not intended for them.

**Comment by LucidComplex** [comment]
I tried what you said, and indeed the issue didn't occur. However, I created 2 clients by copying the directory and running both of them at the same time. I set one of the client to subscribe to Nissans, and the other to Hondas, and the issue occurred there.

**Comment by nirinchev** [comment]
Thanks. With the new instructions, I was able to reproduce it and we'll have a fix shortly.
