### ISSUE TITLE
Starting realm-graphql-service is confusing

### ISSUE THREAD

**Issue by ajonno** [realm/realm-graphql-service#41]
This might just be me, but I spent a while - after installing realm-graphql-service npm package, trying to figure out why I couldn't get a response (from the Realm server) when launching GraphiQL in the browser. 

What I found was that if  (after installing and configuring realm-graphql-service) --> and then restart the server with "ros start" ..... GraphQL didn't work. BUT if I restarted the server with ```npm start``` then BOTH ROS and GraphQL worked (and I could use the GraphiQL console etc.).

Unless I've missed something, I would have thought running ```ros start``` should work. My suggestion would be to make a change to ensure that's the case - or - stipulate clearly somewhere in the docs that running ```ros start``` won't work if you want to also run GraphQL.

**Comment by howdyhyber** [comment]
Hi Ajonno! can i see snippet code your realm-graphq-service configuration? We are using graphql and its working, maybe i could help.

**Comment by ajonno** [comment]
hey, thanks for following up on this! actually is really my bad that i left this open - we are also fine now in terms of using GraphQL via Realm. there is one related open issue atm, but it's for generating React production builds and is a separate ticket.
