### ISSUE TITLE
It there a way to delete an existing field inside the class of our realm?

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-graphql-service#49]
Can we do this in realm? We needed it especially if we manually added the field using Realm Studio and i mistakenly choose the wrong data type for instance. Is this a possible feature in realm? :smiley:

**Comment by nirinchev** [comment]
Synchronized Realms only support additive migrations (i.e. you can't really remove fields or change their type). You can read more about it in the [documentation](https://docs.realm.io/platform/using-synced-realms/migrating-your-data).

If you don't have live apps that use that Realm, it would probably be easiest if you just created a new one.
