### ISSUE TITLE
Error on New ROS

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-graphql-service#51]
I have encountered an error from the latest ROS like this.

Name "\_\_Class" must not begin with "\_\_", which is reserved by GraphQL introspection. In a future release of graphql this will become a hard error.
0|npm      |     at assertValidName (/home/ubuntu/spingine/node_modules/graphql/utilities/assertValidName.js:37:19)
0|npm      |     at new GraphQLObjectType (/home/ubuntu/spingine/node_modules/graphql/type/definition.js:297:42)
0|npm      |     at makeTypeDef (/home/ubuntu/spingine/node_modules/graphql/utilities/buildASTSchema.js:295:12)
0|npm      |     at makeSchemaDef (/home/ubuntu/spingine/node_modules/graphql/utilities/buildASTSchema.js:277:16)
0|npm      |     at typeDefNamed (/home/ubuntu/spingine/node_modules/graphql/utilities/buildASTSchema.js:269:32)
0|npm      |     at /home/ubuntu/spingine/node_modules/graphql/utilities/buildASTSchema.js:187:12
0|npm      |     at Array.map (<anonymous>)
0|npm      |     at Object.buildASTSchema (/home/ubuntu/spingine/node_modules/graphql/utilities/buildASTSchema.js:186:24)
0|npm      |     at buildSchemaFromTypeDefinitions (/home/ubuntu/spingine/node_modules/graphql-tools/dist/schemaGenerator.js:182:28)
0|npm      |     at _generateSchema `(/home/ubuntu/spingine/node_modules/graphql-tools/dist/schemaGenerator.js:97:18)```

**Comment by nirinchev** [comment]
This is a warning, not an error. You should be able to continue working with the service.

**Comment by nirinchev** [comment]
Yes, this is an unfortunate collision between GraphQL semantics and Realm semantics. We'll figure something out before it becomes an error - there's nothing wrong with what you're doing.
