### ISSUE TITLE
Upgrading to the latest ROS

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-graphql-service#54]
I updated my ROS today and this is what happened.

Detected an unhandled promise rejection at:  Promise {
0|npm      |   <rejected> TypeError: next is not a function
0|npm      |     at /home/ubuntu/xeleqt-realm-object-server/node_modules/apollo-server-express/dist/expressApollo.js:25:24
0|npm      |     at <anonymous> } , reason:  TypeError: next is not a function
0|npm      |     at /home/ubuntu/xeleqt-realm-object-server/node_modules/apollo-server-express/dist/expressApollo.js:25:24
0|npm      |     at <anonymous>

I cant query in GraphQL. It keeps on logging the same error everything i try to access GraphQL explore . These are the version of the packages i used:
realm-graphql-service : 2.5.0
realm-object-server : 3.6.6

**Comment by nirinchev** [comment]
I imagine this has happened because ROS couldn't boot up properly. What are the logs when ROS starts?

**Comment by howdyhyber** [comment]
i think the one causing it is the updated version of realm-graphql-service, because when i downgraded the realm-graphql-service to 2.4.0, it works perfectly fine. I will try to comment the previous log, ill try to find it.

**Comment by nirinchev** [comment]
Okay, I've found the problem - it's related to types starting with underscores. We'll fix it and release a new version shortly. In the meantime, you can downgrade to 2.4.0.
