### ISSUE TITLE
Realm 3.6.12 and GraphQL 2.6.0

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-graphql-service#61]
I encountered a waring in ROS, it our apps cant sync. These are the Logs in the ROS:

unknown counter: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.merges.performed - 122945,c
sync8:18:44 AM
unknown counter: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.changeset.integrated - 1,c
sync8:18:45 AM
unknown timing: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.changeset.integrated - 10039,ms
sync8:18:45 AM
unknown timing: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.changeset.integrated.merges - 122945,ms
sync8:18:45 AM
unknown timing: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.changeset.integrated.size - 1528,ms
sync8:18:45 AM
unknown counter: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.merges.performed - 122945,c
sync8:18:54 AM
unknown counter: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.changeset.integrated - 1,c
sync8:18:56 AM
unknown timing: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.changeset.integrated - 10137,ms
sync8:18:56 AM
unknown timing: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.changeset.integrated.merges - 122945,ms
sync8:18:56 AM
unknown timing: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.changeset.integrated.size - 1494,ms
sync8:18:56 AM
unknown counter: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.merges.performed - 122945,c
sync8:19:04 AM
unknown counter: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.changeset.integrated - 1,c
sync8:19:06 AM
unknown timing: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.changeset.integrated - 10216,ms
sync8:19:06 AM
unknown timing: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.changeset.integrated.merges - 122945,ms
sync8:19:06 AM
unknown timing: realm.ip-10-0-0-134.ap-southeast-1.compute.internal.changeset.integrated.size - 1512,ms

**Comment by nirinchev** [comment]
I don't see anything that would indicate an error in these logs. Can you share more info on what exactly you're observing?

**Comment by howdyhyber** [comment]
This happens when the app syncs , those logs wil appear in the ROS.
![sync](https://user-images.githubusercontent.com/22556130/41650425-95e4ed60-74b0-11e8-9e82-c4ffe0cefe54.png)

**Comment by nirinchev** [comment]
@alebsack @simonask do you know what could cause these? Seems like something is wrong with the metrics but I'm not familiar with that part of ROS.

**Comment by alebsack** [comment]
@nirinchev They're warnings that the statsd exporter can't match the statsd name of the metric to the internal translation table for prometheus: https://github.com/realm/realm-object-server-private/blob/master/src/shared/StatsdExporter.ts#L151

These metrics, should, however be matched as we have everything defined. I think he might be getting these errors due to the hostname having multiple dots: https://github.com/realm/realm-object-server-private/blob/master/src/shared/StatsdExporter.ts#L236

**Comment by alebsack** [comment]
Having multiple dots in a machine's hostname is not illegal, but not necessarily good practice. That said, we should create a fix for this.

**Comment by nirinchev** [comment]
Closing this in favor of https://github.com/realm/realm-object-server-private/issues/1143
