### ISSUE TITLE
Upgrade Failed

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-graphql-service#62]
We have encountered an error something like this

HTTP upgrade failed (service did not respond properly) {"type":"https://realm.io/docs/object-server/problems/service-unavailable","title":"The requested service is temporarily unavailable.","status":503,"code":802} Request: a60ae892-e142-4ee6-b6c2-1ffd9182ff93 GET /realm-sync/%2Fxeleqt-production%2F__partial%2F30c7345a92921557b040dbe44fc27f3b%2F7b2039cb4bdf970677d253ec40fe23fdb26923b3 HTTP/1.1 Authorization: Realm-Access-Token version=1 token="eyJhcHBfaWQiOiJjb20uc3BpbmdpbmUueGVsZXF0LmFnZW50IiwiaWRlbnRpdHkiOiIzMGM3MzQ1YTkyOTIxNTU3YjA0MGRiZTQ0ZmMyN2YzYiIsImFjY2VzcyI6WyJkb3dubG9hZCIsInVwbG9hZCJdLCJzYWx0IjoiOWExYzA4NjEiLCJleHBpcmVzIjo0NjgyMDUxOTU2LCJwYXRoIjoiL3hlbGVxdC1wcm9kdWN0aW9uL19fcGFydGlhbC8zMGM3MzQ1YTkyOTIxNTU3YjA0MGRiZTQ0ZmMyN2YzYi83YjIwMzljYjRiZGY5NzA2NzdkMjUzZWM0MGZlMjNmZGIyNjkyM2IzIiwic3luY19sYWJlbCI6ImRlZmF1bHQifQ==:LW3mtqQo0mI3rI5r/qzb6EHQq8OtwQJfrTfgJAxL+yV4QeqzbYZ2GalsT6qkQO9wyqW8v5LrMpPcatLHeBetM/JCao6mDXJ4S4heENNH/J6V1t2jEAS/+SB0lbeZ3RCGZhXrZp09FGmaB+Cvi6t7jK2lngb31wS2jCZ/zI6B7wQgFYVSC2xxoGXX69FZZ00WphCDCadL+jYcKkt7fRt4UabMRgXIYf0wnBY4vpgQttlJquFVkBNSg46ITeGjkc7dYkjI0Vjg17dSxgVRwh+KfV3c04riVWw4Bd0n1WzlptAsNV1rCWS6aRVCLDmkIrUwlPpUuwMeLCHkFZIzxVBnyQ==" Connection: Upgrade Host: 13.229.208.159 Sec-WebSocket-Key: iDpQQyVOF/LEwff7iYRHEg== Sec-WebSocket-Protocol: io.realm.sync.24 Sec-WebSocket-Version: 13 Upgrade: websocket Response: HTTP/1.1 503 Service Unavailable
 Server: Realm-Object-Server/3.6.10
 
http11:19:54 AM
 

ROS Version : 3.6.10 GraphQL : 2.5.1

**Comment by nirinchev** [comment]
This happens when you try to access ROS services before it has fully initialized. You can check if ROS is up and running by executing a `GET https://my-ros-instance/health` request. If this error persists, then it would indicate something went wrong when booting up.
