### ISSUE TITLE
GraphQL Error

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-graphql-service#63]
Good morning!

We tried accessing two different realm paths using graphql/explore. The 1st realm path can successfully query classes, the second realm path displayed "Invalid options provided to ApolloServer: Cannot access realm that has been closed." . Our current way is to restart the server. Is there better way of resolving this scenario?

**Comment by howdyhyber** [comment]
@nirinchev its a different scenario, the realm is not closed because i can still query the other realm path.

**Comment by nirinchev** [comment]
Each Realm path corresponds to a single Realm, whose lifecycle is managed individually. So I'm fairly certain it's the same case - for some reason one of your Realms got into an inconsistent state where a component believes its cached instance is valid and attempts to use it but in reality it is not and I'm super interested in reproducing and fixing that.

**Comment by astigsen** [comment]
Closing this for now as it relates to an outdated version of ROS and there has been no feedback from the user for over a month. Please reopen if it resurfaces.
