### ISSUE TITLE
Error what(): set: row ndx out of range

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-graphql-service#64]
We have encountered an error something like this:

terminate called after throwing an instance of 'realm::sync::BadChangesetError'
0|nextgo-r | what(): set: row ndx out of range
PM2 | App [nextgo-ros] with id [0] and pid [31707], exited with code [0] via signal [SIGABRT]
PM2 | Starting execution sequence in -fork mode- for app name:nextgo-ros id:0
PM2 | App name:nextgo-ros id:0 online

**Comment by nirinchev** [comment]
Please refrain from opening identical issues in multiple repositories - it will not result in faster response times. I'm closing this one as it's not related to the GraphQL service.
