### ISSUE TITLE
Cannot query, mutate or explore a Realm with an empty schema

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-graphql-service#65]
When accessing a Realm with an empty schema via the GraphiQL explorer the service responds with the following error:

> "Invalid options provided to ApolloServer: Syntax Error: Expected Name, found }"

<img width="955" alt="error-screenshot" src="https://user-images.githubusercontent.com/1243959/42420524-4a7d7a2a-82c7-11e8-85cc-e6aac590de40.png">

This is probably because the empty Realm and therefore the empty schema results in an unexpected ApolloServer configuration. When building an app that supports a web-first flow we cannot assume that the realm already has a schema.

**Comment by astigsen** [comment]
@nirinchev is this still relevant?

**Comment by nirinchev** [comment]
Yes

**Comment by nirinchev** [comment]
We're now throwing a more meaningful error.
