### ISSUE TITLE
Invalidate the schema when it changes

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-graphql-service#68]
Would it be possible to use [Realm JS's `addListener` method](https://realm.io/docs/javascript/latest/api/Realm.html#addListener) to listen for changes to the schema and invalidate the schema cache when it changes?

**Comment by nirinchev** [comment]
We already do that, but the realm has to be open for it to work.

**Comment by kraenhansen** [comment]
Oh okay - I couldn't find the code for it .. but thanks :)

**Comment by nirinchev** [comment]
Here it is: https://github.com/realm/realm-graphql-service/blob/master/src/service.ts#L879
