### ISSUE TITLE
Allow GraphQL configuration via the configuration Realm

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-graphql-service#87]
[Requested by a user](https://forum.realm.io/t/set-presentintsasfloatsinschema-in-realm-cloud-graphql/2319) and technically not super challenging. It also makes sense, as none of the config options are something that needs to be set once and for all.

**Comment by bmunkholm** [comment]
@nirinchev Estimate?

**Comment by nirinchev** [comment]
Exposing the API should be doable in less than a day. A follow up would be a studio/cloud portal UI to actually consume the API. Technically, impatient users can use Studio to directly edit the content of the configuration Realm, so even without a UI, the feature could be useful.
