### ISSUE TITLE
Invalid options provided to ApolloServer: User is no longer valid.

### ISSUE THREAD

**Issue by cclinh** [realm/realm-graphql-service#94]
We have a web app that connect to a production realm server using GraphQL. Its working normally for months.
Recently, we can't connect to realm server using graphql. The error response is:
`Invalid options provided to ApolloServer: User is no longer valid.`

has anyone run into the same problem?

**Comment by nirinchev** [comment]
How are you authenticating the user?

**Comment by cclinh** [comment]
@nirinchev I followed the instruction here
https://docs.realm.io/sync/graphql-web-access/using-the-graphql-client
```
const credentials = Credentials.usernamePassword('SOME-USERNAME', 'SOME-PASSWORD');
const user = await User.authenticate(credentials, 'http://my-ros-instance:9080');
```
Its worth mentioning that it has worked normally before and the error occurs on realm studio as well

**Comment by nirinchev** [comment]
Hm... Do you use query based sync via graphql? If you're using the legacy Realm Cloud, can you open a support ticket and ask the team to restart your graphql service? If you're self hosting ROS, can you try restarting it yourself?

**Comment by cclinh** [comment]
@nirinchev  Thanks for your  support. I opened a ticket to realm support team and got the answer that it was a server issue in us1 region. 
The graphql server is working normally now. 
This is not an issue with realm graphql client so I'll close this issue
